name: shaver
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  #  replace sdk from ">=2.15.1 <3.0.0" to ">=2.7.1 <3.0.0" because i don't found any package
  #  support the vibration with custom duration
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # ***  Device Services Packages ***

  # For handling Vibration API on iOS, Android, and web.
  # (null safety not support)
  vibration: ^1.7.3

  # For handling Vibration API on iOS, Android, and web.
  # (not support setting vibration duration)
#  flutter_vibrate: ^1.3.0

  # ***  UI Helper Packages ***
  # Toast widget that like toast in native android
  # It like snack bar used to show the user short massage
  fluttertoast: ^8.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/